# Numpy Full Course

# Module 1: Introduction to Numpy

In [1]:
!pip install numpy

In [2]:
import numpy as np

# Module 2: Numpy Basics

In [3]:
import numpy as np
# Creating a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr_1d)
# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:")
print(arr_2d)

1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# Array attributes
print("Shape of arr_1d:", arr_1d.shape)
print("Shape of arr_2d:", arr_2d.shape)
print("\nNumber of elements in arr_1d:", arr_1d.size)
print("Number of elements in arr_2d:", arr_2d.size)
print("\nData type of arr_1d:", arr_1d.dtype)
print("Data type of arr_2d:", arr_2d.dtype)

Shape of arr_1d: (5,)
Shape of arr_2d: (3, 3)

Number of elements in arr_1d: 5
Number of elements in arr_2d: 9

Data type of arr_1d: int32
Data type of arr_2d: int32


In [5]:
# Indexing
print("First element of arr_1d:", arr_1d[0])
print("Element at row 1, column 2 of arr_2d:", arr_2d[1, 2])
# Slicing
print("\nSlicing arr_1d from index 1 to 3:", arr_1d[1:4])
print("Slicing arr_2d to get the first two rows and columns:", arr_2d[:2, :2])

First element of arr_1d: 1
Element at row 1, column 2 of arr_2d: 6

Slicing arr_1d from index 1 to 3: [2 3 4]
Slicing arr_2d to get the first two rows and columns: [[1 2]
 [4 5]]


In [6]:
# Element-wise operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# Addition
result_add = arr1 + arr2
print("\nElement-wise addition:")
print(result_add)
# Multiplication
result_mul = arr1 * arr2
print("\nElement-wise multiplication:")
print(result_mul)



Element-wise addition:
[5 7 9]

Element-wise multiplication:
[ 4 10 18]


# Module 3: Advanced Array Operations

In [7]:
import numpy as np
# Creating an array
arr = np.array([1, 2, 3, 4, 5])
# Square root using ufunc
result_sqrt = np.sqrt(arr)
print("Square root of arr:", result_sqrt)
# Trigonometric functions using ufunc
result_sin = np.sin(arr)
result_cos = np.cos(arr)
print("\nSin of arr:", result_sin)
print("Cos of arr:", result_cos)

Square root of arr: [1.         1.41421356 1.73205081 2.         2.23606798]

Sin of arr: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cos of arr: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [8]:
# Math operations with ufuncs
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# Element-wise addition
result_add = np.add(arr1, arr2)
print("\nElement-wise addition using ufunc:")
print(result_add)
# Element-wise multiplication
result_mul = np.multiply(arr1, arr2)
print("\nElement-wise multiplication using ufunc:")
print(result_mul)


Element-wise addition using ufunc:
[5 7 9]

Element-wise multiplication using ufunc:
[ 4 10 18]


In [9]:
# Aggregation functions
arr = np.array([1, 2, 3, 4, 5])
# Sum of all elements
sum_arr = np.sum(arr)
print("\nSum of arr:", sum_arr)
# Mean of all elements
mean_arr = np.mean(arr)
print("Mean of arr:", mean_arr)
# Median of arr
median_arr = np.median(arr)
print("Median of arr:", median_arr)
# Minimum and maximum elements
min_arr = np.min(arr)
max_arr = np.max(arr)
print("Minimum of arr:", min_arr)
print("Maximum of arr:", max_arr)


Sum of arr: 15
Mean of arr: 3.0
Median of arr: 3.0
Minimum of arr: 1
Maximum of arr: 5


In [10]:
# Axis-wise operations
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
# Sum along columns (axis=0)
sum_columns = np.sum(arr_2d, axis=0)
print("\nSum along columns:")
print(sum_columns)
# Mean along rows (axis=1)
mean_rows = np.mean(arr_2d, axis=1)
print("Mean along rows:")
print(mean_rows)


Sum along columns:
[5 7 9]
Mean along rows:
[2. 5.]
